version: '2'

services:
  terraform:
    image: hashicorp/terraform:light
    volumes:
      - ${PWD}/terraform:/terraform
    working_dir: "/terraform"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
