AWSTemplateFormatVersion: "2010-09-09"
Description: Create WordPress on Amazon Lightsail

Resources:
  WordPressServer: 
    Type: AWS::Lightsail::Instance
    CreationPolicy: 
      ResourceSignal:
        Timeout: PT10M # Specify the time here
    Properties:
      BlueprintId: amazon_linux_2
      BundleId: nano_2_0
      InstanceName: WordPressServer
      AvailabilityZone: ap-northeast-1a
      Networking:
        Ports:
          - FromPort: 443
            ToPort: 443
          - FromPort: 80
            ToPort: 80
          - FromPort: 22
            ToPort: 22
      UserData:
        |
          #!/bin/bash -ex
          yum install -y git
          amazon-linux-extras install -y ansible2
          git clone https://github.com/eskimo220/create-lightsail
          ansible-playbook ./create-lightsail/playbook.yml

#   WordPressIp:
#     Type: AWS::Lightsail::StaticIp
#     Properties: 
#       AttachedTo: WordPressServer
#       StaticIpName: WordPressIp

# Outputs:
#   WordPressIp:
#     Description: WordPressIp
#     Value: !GetAtt WordPressIp.IpAddress